# Configuration for mChartAnalyzer

# Artists whose songs will be analyzed
artists:
  - James Brown

# If true, log files will be written for each run of the program
# The logs will be located in the "mchartanalyzer-output" directory
logEnabled: true

# If true, the system will stop parsing after a few charts. (3 per artist, to be exact)
# This should be set to "false" for normal operation.
# When running the main script, this option can be overriden by the --test-mode or --normal-mode flags
testModeEnabled: true

# If false, the system will ignore the cooldown period after a URL is scraped.
# Default value is "true"
# Normally, the system waits one month before scraping a URL again.
scrapeCooldownEnabled: true
